package com.platform.smartwastemanager.features.report.data

import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.firestore.Query
import com.platform.smartwastemanager.core.util.Constants
import com.platform.smartwastemanager.features.report.domain.WasteReport
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.flow.catch
import kotlinx.coroutines.tasks.await

/**
 * Handles all Firestore operations for waste_reports collection.
 * - submitReport: adds a new document
 * - getPendingReports: live stream of all "pending" reports
 * - dismissReport: permanently deletes a report document
 */
class ReportRepository {

    private val firestore = FirebaseFirestore.getInstance()

    // Reference to the waste_reports collection
    private val collection = firestore.collection(Constants.COLLECTION_WASTE_REPORTS)

    /**
     * Saves a new waste report to Firestore.
     * The document ID is auto-generated by Firestore and then written
     * back into the "id" field of the document.
     */
    suspend fun submitReport(report: WasteReport): Result<Unit> {
        return try {
            // Create a new document reference (generates a unique ID)
            val docRef = collection.document()

            // Build the map to store — we use the generated docRef.id as the report's ID
            val data = mapOf(
                "id"         to docRef.id,
                "category"   to report.category,
                "reportType" to report.reportType,
                "location"   to report.location,
                "streetName" to report.streetName,
                "reportedBy" to report.reportedBy,
                "timestamp"  to report.timestamp,
                "status"     to report.status
            )

            docRef.set(data).await()
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    /**
     * Returns a live stream of all PENDING waste reports.
     * Uses callbackFlow to convert Firestore's snapshot listener into a Flow.
     *
     * IMPORTANT (Rule 4): Never call close(error) — use trySend(emptyList()) on failure.
     */
    fun getPendingReports(): Flow<List<WasteReport>> = callbackFlow {
        val listener = collection
            .whereEqualTo(Constants.FIELD_STATUS, Constants.FIELD_STATUS_PENDING)
            .orderBy("timestamp", Query.Direction.DESCENDING)
            .addSnapshotListener { snapshot, error ->
                if (error != null) {
                    // Rule 4: do NOT close(error) — just send an empty list
                    trySend(emptyList())
                    return@addSnapshotListener
                }

                val reports = snapshot?.documents?.mapNotNull { doc ->
                    try {
                        WasteReport(
                            id         = doc.getString("id") ?: doc.id,
                            category   = doc.getString("category") ?: "",
                            reportType = doc.getString("reportType") ?: "",
                            location   = doc.getGeoPoint("location")
                                ?: com.google.firebase.firestore.GeoPoint(0.0, 0.0),
                            streetName = doc.getString("streetName") ?: "",
                            reportedBy = doc.getString("reportedBy") ?: "",
                            timestamp  = doc.getTimestamp("timestamp")
                                ?: com.google.firebase.Timestamp.now(),
                            status     = doc.getString("status") ?: "pending"
                        )
                    } catch (e: Exception) {
                        null // Skip malformed documents
                    }
                } ?: emptyList()

                trySend(reports)
            }

        // When the flow is cancelled (e.g. ViewModel cleared), remove the listener
        awaitClose { listener.remove() }
    }.catch {
        // If anything upstream throws, emit an empty list instead of crashing
        emit(emptyList())
    }

    /**
     * Permanently deletes a report from Firestore.
     * Called by drivers to remove a pin from the map and route results.
     */
    suspend fun dismissReport(reportId: String): Result<Unit> {
        return try {
            collection.document(reportId)
                .delete()
                .await()
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }
}
